# Explore here

In [1]:
#===============================================================================
#                Cargar Archivos
#===============================================================================

# Your code here
import pandas as pd

Ruta_Arch = "https://raw.githubusercontent.com/4GeeksAcademy/decision-tree-project-tutorial/main/diabetes.csv"

total_data= pd.read_csv(Ruta_Arch, sep = ",")
total_data.head(200)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
195            5      158             84             41      210  39.4   
196            1      105             58              0        0  24.3   
197            3      107             62             13       48  22.9   
198            4      109             64             44       99  34.8   
199            4      148             60             27      318  30.9   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
195                     0.395   29        1  
196                     0.187   21        0  
197                     0.678   23        1  
198                     0.905   26        1  
199                     0.150   29        1  

[200 rows x 9 columns]

In [6]:
#===============================================================================
#                Estudio Unidimensional
#===============================================================================


# Obtener información sobre tipos de datos y valores no nulos
total_data.info()

#descripcion
total_data.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:

#===============================================================================
#                Missing Data Ceros, N/A
#===============================================================================
# Count NaN
total_data.isnull().sum().sort_values(ascending=False)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Como primera Conclusion obtenida del describese observa que Hay datos de min = 0 En Campos que no tienen Sentido: Presion arterial (BloodPressure), Indice de MAsa Corporea (BMI), Glucosa, Grosor de la piel (SkinThickness)



Lo siguiente que vemos es que no hay datos Null.

In [8]:
total_data.drop(total_data[total_data['BMI'] == 0].index, inplace=True)
total_data.drop(total_data[total_data['BloodPressure'] == 0].index, inplace=True)
total_data.drop(total_data[total_data['Glucose'] == 0].index, inplace=True)
total_data.drop(total_data[total_data['SkinThickness'] == 0].index, inplace=True)
total_data.drop(total_data[total_data['Insulin'] == 0].index, inplace=True)

In [11]:
total_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 3 to 765
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               392 non-null    int64  
 1   Glucose                   392 non-null    int64  
 2   BloodPressure             392 non-null    int64  
 3   SkinThickness             392 non-null    int64  
 4   Insulin                   392 non-null    int64  
 5   BMI                       392 non-null    float64
 6   DiabetesPedigreeFunction  392 non-null    float64
 7   Age                       392 non-null    int64  
 8   Outcome                   392 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 30.6 KB


In [12]:
total_data.shape

(392, 9)

Los Datos se redujeros de 768 Registros a  392 Registros